language: java

env:
  global:
    - CODECOV_TOKEN="b5659ea0-f191-4e1d-9139-a8a31971c386"

install: true

# TODO investigate using build stages instead of matrix

# TODO stages.* to specify conditions for deploy stage

jobs:
  include:
    - stage: test
      name: "Unit Tests Java 8"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk8
      install: &build_no_checks
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dchecksyle.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -B dependency:go-offline
      script: &build_with_unittests
        - mvn install -pl \!tests/acceptance-test -P reduce-logging -o || travis_terminate 1

    - name: "Unit Tests Java 11"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk11
      install: *build_no_checks
      script: *build_with_unittests

    - name: "Acceptance Tests Java 8"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk8
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P reduce-logging -o || travis_terminate 1

    #Default
    - name: "Acceptance Tests Java 11"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk11
#      before_install:
#        - rm "${JAVA_HOME}/lib/security/cacerts"
#        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P reduce-logging || travis_terminate 1

    - name: "GRPC Only Acceptance Tests"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk8
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P grpc-acceptance-tests,reduce-logging -o || travis_terminate 1

    - name: "Simple Only Acceptance Tests"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk8
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P simple-acceptance-tests,reduce-logging -o || travis_terminate 1

    - name: "Vault Acceptance Tests Java 8"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk8
      before_install: &install_hashicorp
        - wget https://releases.hashicorp.com/vault/1.0.1/vault_1.0.1_linux_amd64.zip -O /tmp/vault_1.0.1_linux_amd64.zip
        - mkdir -p vault/bin && pushd $_
        - unzip /tmp/vault_1.0.1_linux_amd64.zip
        - export PATH=$PATH:$PWD && popd
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P vault-acceptance-tests,reduce-logging -o || travis_terminate 1

    - name: "Vault Acceptance Tests Java 11"
      #if: type = pull_request OR type = api
      if: type = pull_request
      jdk:  oraclejdk11
      before_install: *install_hashicorp
      install: *build_no_checks
      script: mvn verify -pl tests/acceptance-test -P vault-acceptance-tests,reduce-logging -o || travis_terminate 1

    - stage: deploy
      name: "Deploy to OSSRH"
      if: branch = master AND type = push
      jdk:  oraclejdk8
      script:
        - echo "Job will run..."
#        - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
#        - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
#        - mvn deploy --settings .maven.xml -P release,reduce-logging -q || travis_terminate 1

    - stage: "Release and Deploy"
      name: "Tag on GitHub and deploy to OSSRH"
      if: type = api
      jdk:  oraclejdk8
      script:
        - |
          head_ref=$(git rev-parse HEAD) || travis_terminate 1
          branch_ref=$(git rev-parse "$TRAVIS_BRANCH") || travis_terminate 1
          if [[ $head_ref != $branch_ref ]]; then
            echo "HEAD ref ($head_ref) does not match $TRAVIS_BRANCH ref ($branch_ref).  New commits may have been pushed before the build cloned the repo"
          return 0
          fi
          git checkout $TRAVIS_BRANCH || travis_terminate 1

          release_version=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec`
          branch_name="release-${release_version}"

#         prepare current branch for release, create release branch, increment development version on current branch
          mvn --settings .maven.xml -B -DbranchName=${branch_name} release:branch || travis_terminate 1

#         checkout release branch
          git checkout $branch_name || travis_terminate 1

#        - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
#        - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
#        - release_version=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec`
#        - branch_name="release-${release_version}"
#        - git checkout -b $branch_name  || travis_terminate 1
        # make batch/offline i.e. provide version, tag, next dev version as CLI args etc.
#        - mvn --settings .maven.xml -B -DpushChanges=true release:prepare || travis_terminate 1
#        - mvn --settings .maven.xml -B -DpushChanges=true release:perform || travis_terminate 1
#        - echo "TODO: The release branch $branch_name must be manually merged back to master."

#    - if: branch = travis_changes AND type = push
#      name: "Deploy site"
#      jdk:  oraclejdk8
#      before_install:
#        - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
#      script:
#          - mvn site-deploy
#      install: echo "install"

sudo: enabled

#notifications:
#  slack:
#    secure: TeWK06kSrpdvMY/TNocbNYy0gJ9+jP9ygjzBtgsMRmm0kbBpzg34eZJyWMU/sf5x6taWAVOGW1jfG4+kfLUqG7CrqcRUihqK3x1DOJQS/BlT2IhJkED4dtwEw7xTkRTxPkghwMAXjJZImnh7ORS1HCJByEs5kedThh/Vr1HDaWJ+KctGLhE3LudyYikxZEWYVbexHZ5o8QbFGwmTYNHLaKAIGZbvt8wDoE+yJOftCqmCh2aJ4YBzYSW9wmxxf3tu75Azni9Am1wiCu+Q5NhljtZwbx6QopkHxbM0DdohOwQQ1g2lPni8dZYdw/obvVQOKLNjkTWU3LvtiWrwiAKp/w5czeL5nkQiFxcAcyTqCRXNh3J1RD1k9H4OBLo2N+5o6dhnNUZt24PZFsNMzR+ygmNq7WvAqQpC5ixppND//8tg25234dXafdL8KmWMFuTepQem2H9Yo8zr16v+VC7MEUyh5ta67xqhFGluIDEySgxMX389r0bU1dXsqhc/K131ty6AcV8FWEGToguvxL+Sj8RhBk5F2B+QOtUzl/5iqlGhqpWcVkoQjiCPJbcLHlHbt6fiUNEpVVjxa2kNrTNZ/5GS6eZoVr5OT1tc3lY5ZUA40yk0Pk63mYB30yMl/wtbbQl/g/0OpcJW20+ZT3971dIt6PMFg3b+n1xSZgTNvIY=

cache:
  directories:
    - "$HOME/.m2"

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

