name: Tessera Docker Dry Run

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    name: Build Docker image without pushing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.NOT_A_SECRET_THAT_I_KNOW }}
          push: false