name: Tessera Release Build

on:
  repository_dispatch:
    types: [release]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create release branch
        run: |
          git config user.name "quorumbot"
          export now=`date +%Y%m%d%H%M%S`
          git checkout -b "release-$now"
      - name: Release Prepare
        run: |
          mvn --settings .maven.xml release:prepare -DskipTests -Darguments="-DskipTests"
      - name: Release Perform
        run: |
          echo "${GPG_SECRET_KEYS}" | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
          mvn --settings .maven.xml -DskipTests -Darguments="-DskipTests -Dmaven.deploy.skip=true -Dgpg.skip=true" -DworkingDirectory=${GITHUB_WORKSPACE}/release-checkout release:perform
      - name: Save tessera-app.jar
        uses: actions/upload-artifact@v2
        with:
          name: tessera-app
          path: ${GITHUB_WORKSPACE}/release-checkout/tessera-dist/tessera-app/target/tessera-app-*-app.jar
      - name: Determine tag name
        id: tag
        run: |
          echo ::set-output name=full-ver::$(echo $REF | sed -e 's/^.*tessera-app-\(.*\)-app.jar$/\1/g')
          echo ::set-output name=minor-ver::$(echo $REF | sed -e 's/^.*tessera-app-\([[:digit:]]*\.[[:digit:]]*\).*-app.jar$/\1/g')
      - name: Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: ${{ steps.tag.outputs.full-ver }}, ${{ steps.tag.outputs.minor-ver }}
          add_git_labels: true
          dockerfile: ${GITHUB_WORKSPACE}/release-checkout/.github/workflows/noBuild.Dockerfile
          path: ${GITHUB_WORKSPACE}/release-checkout/tessera-dist/tessera-app/target
          build_args: JAR_FILE=tessera-app-${{ steps.tag.outputs.full-ver }}-app.jar
