name: Tessera Release Build

on:
  repository_dispatch:
    types: [release]
  push:
    branches: [increment-version-auto-pr]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release
        id: release
        run: |
          git config user.name "quorumbot"
          now=`date +%Y%m%d%H%M%S`
          tagversion=`cat version.txt | cut -d'-' -f1`
          tagname="tessera-$tagversion"
          echo "$tagversion" > version.txt
          git add version.txt
          git commit -m "Change to release version $tagversion"

          ./gradlew incrementProjectVersion --info
          git add version.txt
          git commit -m "Change version to next development version"

          minor_version=${tagversion%.*}
          echo ::set-output name=full-ver::$tagversion
          echo ::set-output name=minor-ver::$minor_version
          echo ::set-output name=branch-name::release-$now
      - name: Create PR to update development version
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.release.outputs.branch-name }}
          title: Update development version
          body: Triggered by release https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
