name: Tessera Release Build

on:
  push:
    branches:
      - test-dist-release

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}

jobs:
  checkdependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew dependencyCheckAnalyze -x test
  release_sonatype:
    needs: checkdependencies
    runs-on: ubuntu-latest
    outputs:
      full-ver: ${{ steps.release.outputs.full-ver }}
      minor-ver: ${{ steps.release.outputs.minor-ver }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release
        id: release
        run: |
          git config user.name "quorumbot"
          now=`date +%Y%m%d%H%M%S`
          tagversion=`cat version.txt | cut -d'-' -f1`
          tagname="tessera-$tagversion"
          echo "$tagversion" > version.txt
          git add version.txt
          git commit -m "Change to release version $tagversion"
          git tag -a $tagname -m "Release tessera $tagversion"
          git push --tags

          ./gradlew build -x test

          minor_version=${tagversion%.*}
          echo ::set-output name=full-ver::$tagversion
          echo ::set-output name=minor-ver::$minor_version
          echo ::set-output name=branch-name::release-$now
      - name: Upload tessera dists
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: tessera-dists
          path: /home/runner/work/tessera/tessera/tessera-dist/build/distributions/

  release_docker:
    needs: release_sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from SCM
        uses: actions/checkout@v2
      - name: Download tessera dist
        uses: actions/download-artifact@v2
        with:
          name: tessera-dists
          path: /home/runner/work/tessera/tessera/tessera-dist/build/distributions/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Get current date-time (RFC 3339 standard)
        id: date
        run: echo "::set-output name=now::$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ secrets.DOCKER_REPO }}/latest
            ${{ secrets.DOCKER_REPO }}/${{needs.release.outputs.minor-ver}}
            ${{ secrets.DOCKER_REPO }}/${{needs.release.outputs.full-ver}}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.date.outputs.now }}
          push: true
          file: .github/workflows/noBuild.Dockerfile
          context: /home/runner/work/tessera/tessera/tessera-dist/build/distributions/
