name: Trigger OpenAPI document update
on:
  push:
    branches:
      - master
    paths:
      - 'tessera-jaxrs/**'
jobs:
  trigger:
    name: Trigger workflow on doc.tessera repo
    runs-on: ubuntu-latest
    steps:
      - name: Fire repository_dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ConsenSys/doc.tessera
          token: ${{ secrets.QUORUMBOT_PAT }}
          event-type: jaxrs-files-updated
          client-payload: '{"repo": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "openapi-path": "tessera-jaxrs/generate-openapi/build/generated-resources/openapi.yaml"}'
